### ISSUE TITLE
No logs found on Loki

### ISSUE THREAD

**Issue by androna-xm** [joe-elliott/tempo-otel-example#6]
When i choose the Loki datasource and execute `{container_name="tempootelexample_tracing-example_1"} | logfmt  ` it doesn't return any results . ( Although i can see the data from prometheus and tempo datasource and i have installed and enabled the docker-loki-driver plugin ) . Any ideas what might have gone wrong? Thank you in advance!

**Comment by joe-elliott** [comment]
I just did a quick check and I'm seeing logs as expected. I wonder if the issue is that different versions of docker are going to create different container names?

Try using the labels dropdown to see if the logs are there but accessible using a different query:

![image](https://user-images.githubusercontent.com/2272392/120360249-8d0a8980-c2d6-11eb-93e8-af2702dc080b.png)

**Comment by androna-xm** [comment]
Indeed the container names were different, as i saw from the labels dropdown. Thank you !
